INSERT INTO ref.travel_zones (zone_id, zone_name, description)
VALUES
  (1,  'Zone 1',
   'Metro core. Example Zone-1 stations include Southern Cross, Flinders Street, Richmond, North Melbourne, Caulfield, Essendon, Footscray. Boundary overlap: Sunshine is marked 1/2.'),
  (2,  'Zone 2',
   'Metro outer + commuter fringe. Example Zone-2 stations include Deer Park, Ardeer, Rockbank, Caroline Springs, Melton, Cobblebank, Watergardens, Sunbury, Clayton, Dandenong, Broadmeadows, Craigieburn, Donnybrook, Tarneit, Wyndham Vale, Little River, Pakenham, Berwick. Start boundary overlap: Sunshine is 1/2. End boundary overlaps toward regional: Bacchus Marsh is 2/3, Riddells Creek is 2/3, Lara is 2/3/4.'),
  (3,  'Zone 3',
   'Inner regional fringe (between Zones 2 and 4). Overlap examples: Bacchus Marsh is 2/3; Riddells Creek is 2/3. Toward Zone 4: Gisborne 3/4, Macedon 3/4, North Shore 3/4, Corio 3/4, North Geelong 3/4, Kilmore East 3/4, Tynong 3/4.'),
  (4,  'Zone 4',
   'Regional band around Geelong/corridor. Examples: Geelong is 4; Marshall is 4; Waurn Ponds is shown with 4. Overlaps: North Geelong 3/4; Corio 3/4; North Shore 3/4; Gisborne 3/4; Macedon 3/4; Ballan 4/5; Woodend 4/5. Multi-overlap: Lara is 2/3/4.'),
  (5,  'Zone 5',
   'Regional band between Zones 4 and 6. Overlaps on multiple corridors: Woodend 4/5, Ballan 4/5, Broadford 4/5, Garfield 4/5, Bunyip 4/5. Toward Zone 6: Tallarook 5/6 and Longwarry 5/6.'),
  (6,  'Zone 6',
   'Regional band. Examples: Seymour is 6; Drouin is 6. Overlaps: Tallarook 5/6, Longwarry 5/6; Kyneton 6/7; Warragul 6/7.'),
  (7,  'Zone 7',
   'Regional band between Zones 6 and 8. Overlaps: Kyneton 6/7; Warragul 6/7. Toward Zone 8: Malmsbury 7/8.'),
  (8,  'Zone 8',
   'Regional band. Examples: Ballarat is 8; Wendouree is 8; Yarragon is 8. Overlaps: Malmsbury 7/8; Trafalgar 8/9.'),
  (9,  'Zone 9',
   'Regional band (used in multiple corridors). Overlap examples: Trafalgar 8/9; Castlemaine 9/10; Moe 9/10. The map also labels several regional endpoints with 9 (e.g., Sale, Bairnsdale, Echuca, Shepparton, Swan Hill).'),
  (10, 'Zone 10',
   'Regional band adjacent to Zone 9. Overlap examples: Castlemaine 9/10 and Moe 9/10 mark the boundary between Zones 9 and 10.'),
  (11, 'Zone 11',
   'Regional band. Example: Morwell is labelled 11.'),
  (12, 'Zone 12',
   'Regional band. Example: Traralgon is labelled 12. Overlap toward Zone 13: Kangaroo Flat is 12/13.'),
  (13, 'Zone 13',
   'Regional band around Bendigo corridor. Examples: Bendigo is 13; Epsom is 13; Eaglehawk is 13. Overlaps: Kangaroo Flat 12/13; Huntly 13/14; Goornong 13/14.'),
  (14, 'Zone 14',
   'Regional band adjacent to Zone 13. Overlaps: Huntly 13/14; Goornong 13/14.'),
  (15, 'Zone 15',
   'Outer regional band. Overlap: Raywood is 15/16.'),
  (16, 'Zone 16',
   'Outermost regional band. Overlap: Raywood is 15/16.')
ON CONFLICT (zone_id) DO UPDATE
SET zone_name   = EXCLUDED.zone_name,
    description = EXCLUDED.description;
